// ─── User / Auth types ────────────────────────────────────────────────────────

export type UserRole = 'user' | 'admin'

export interface User {
  id: string
  name: string
  email: string
  role: UserRole
  avatarInitials: string
  homeAirport?: string
  travelPreferences?: string[]
}

export const mockUsers: User[] = [
  {
    id: 'user-1',
    name: 'Ria Gupta',
    email: 'rgupta448@gatech.edu',
    role: 'user',
    avatarInitials: 'RG',
    homeAirport: 'ATL',
    travelPreferences: ['Cultural', 'Gastronomy', 'Wellness', 'Luxury'],
  },
  {
    id: 'user-2',
    name: 'Alex Chen',
    email: 'alex.chen@example.com',
    role: 'user',
    avatarInitials: 'AC',
    homeAirport: 'SFO',
    travelPreferences: ['Adventure', 'Hiking', 'Budget'],
  },
  {
    id: 'admin-1',
    name: 'Vayka Admin',
    email: 'admin@vayka.ai',
    role: 'admin',
    avatarInitials: 'VA',
  },
]

// ─── Trip / Itinerary types ───────────────────────────────────────────────────

export type TripStatus = 'upcoming' | 'planning' | 'completed' | 'draft'
export type EventType = 'flight' | 'hotel' | 'meal' | 'activity' | 'transport'
export type EventStatus = 'confirmed' | 'pending' | 'suggested'

export interface TimelineEvent {
  id: string
  type: EventType
  time: string
  endTime?: string
  title: string
  description: string
  location?: string
  cost?: number
  currency: string
  bookingRef?: string
  status: EventStatus
}

export interface ItineraryDay {
  dayNumber: number
  date: string
  dayLabel: string
  events: TimelineEvent[]
}

export interface Itinerary {
  id: string
  userId: string
  planningProgress: number
  slug: string
  title: string
  destination: string
  country: string
  coverImage: string
  dates: { start: string; end: string }
  duration: number
  status: TripStatus
  budget: {
    total: number
    currency: string
    breakdown: { lodging: number; food: number; transport: number; activities: number }
  }
  travelers: number
  travelType: string
  tags: string[]
  aiMatchScore: number
  lastEdited: string
  days: ItineraryDay[]
}

export const itineraries: Itinerary[] = [
  {
    id: '1',
    userId: 'user-1',
    planningProgress: 88,
    slug: 'kyoto-spring',
    title: 'Spring Blossoms & Zen Gardens',
    destination: 'Kyoto, Japan',
    country: 'Japan',
    coverImage: 'https://picsum.photos/seed/kyoto-spring/1200/800',
    dates: { start: 'May 2, 2026', end: 'May 10, 2026' },
    duration: 8,
    status: 'upcoming',
    budget: { total: 5200, currency: 'USD', breakdown: { lodging: 2400, food: 1000, transport: 1200, activities: 600 } },
    travelers: 2,
    travelType: 'Cultural',
    tags: ['Historical', 'Temples', 'Cherry Blossoms', 'Tea Ceremony'],
    aiMatchScore: 97,
    lastEdited: '3 days ago',
    days: [
      {
        dayNumber: 1,
        date: 'Friday, May 2',
        dayLabel: 'Arrival in Kyoto',
        events: [
          {
            id: 'k1-1',
            type: 'flight',
            time: '08:30',
            endTime: '14:20',
            title: 'Flight SFO → KIX (UA837)',
            description: 'United Airlines nonstop from San Francisco to Osaka Kansai. Business class with ANA codeshare.',
            location: 'San Francisco → Osaka',
            cost: 1840,
            currency: 'USD',
            bookingRef: 'UA-884921',
            status: 'confirmed',
          },
          {
            id: 'k1-2',
            type: 'transport',
            time: '15:30',
            title: 'Haruka Express to Kyoto Station',
            description: 'Haruka Limited Express #33 from Kansai Airport to Kyoto Station. Reserved seat in green car. ~75 min.',
            location: 'KIX → Kyoto Station',
            cost: 30,
            currency: 'USD',
            bookingRef: 'JR-K00231',
            status: 'confirmed',
          },
          {
            id: 'k1-3',
            type: 'hotel',
            time: '17:00',
            title: 'Check-in: Hiiragiya Ryokan',
            description: 'Traditional ryokan in Nakagyo Ward, operating since 1818. Tatami rooms with futon, yukata, and kaiseki dinner included.',
            location: 'Nakagyo-ku, Kyoto',
            cost: 420,
            currency: 'USD',
            bookingRef: 'HIR-2025-0502',
            status: 'confirmed',
          },
          {
            id: 'k1-4',
            type: 'meal',
            time: '19:30',
            title: 'Welcome Kaiseki Dinner',
            description: 'Eight-course kaiseki at the ryokan\'s private dining room. Spring menu: bamboo shoots, sakura tofu, seared Wagyu, miso soup.',
            location: 'Hiiragiya Ryokan',
            cost: 180,
            currency: 'USD',
            status: 'confirmed',
          },
        ],
      },
      {
        dayNumber: 2,
        date: 'Saturday, May 3',
        dayLabel: 'Fushimi Inari & Nishiki Market',
        events: [
          {
            id: 'k2-1',
            type: 'activity',
            time: '06:30',
            endTime: '10:00',
            title: 'Sunrise Hike: Fushimi Inari Shrine',
            description: 'Beat the crowds with an early hike through 10,000 vermillion torii gates. Trail to the summit offers panoramic city views over Kyoto.',
            location: 'Fushimi Ward, Kyoto',
            cost: 0,
            currency: 'USD',
            status: 'confirmed',
          },
          {
            id: 'k2-2',
            type: 'meal',
            time: '10:30',
            title: 'Breakfast at Vermillion Café',
            description: 'Third-wave coffee and Japanese breakfast sets — tamago, miso, and seasonal pickles — steps from the Inari trailhead.',
            location: 'Fushimi, Kyoto',
            cost: 22,
            currency: 'USD',
            status: 'suggested',
          },
          {
            id: 'k2-3',
            type: 'activity',
            time: '13:00',
            endTime: '15:00',
            title: 'Nishiki Market Guided Food Tour',
            description: 'Private walking tour of the "Kitchen of Kyoto." Sample yuba, pickled plums, fresh tofu, tamagoyaki, and hojicha ice cream.',
            location: 'Nishiki Market, Nakagyo-ku',
            cost: 85,
            currency: 'USD',
            bookingRef: 'NMT-20250503',
            status: 'confirmed',
          },
          {
            id: 'k2-4',
            type: 'meal',
            time: '19:00',
            title: 'Kikunoi (Michelin ★★)',
            description: '12-course kaiseki omakase showcasing spring ingredients: sansai mountain vegetables, sakura-smoked duck, and fresh river sweetfish.',
            location: 'Higashiyama, Kyoto',
            cost: 240,
            currency: 'USD',
            bookingRef: 'KKN-1203',
            status: 'confirmed',
          },
        ],
      },
      {
        dayNumber: 3,
        date: 'Sunday, May 4',
        dayLabel: 'Arashiyama Bamboo & Tea',
        events: [
          {
            id: 'k3-1',
            type: 'transport',
            time: '09:00',
            title: 'Sagano Scenic Railway',
            description: 'Panoramic open-air train through the Hozu River gorge to Arashiyama. 7.3 km of steep mountains and mossy cliffs.',
            location: 'Kyoto → Arashiyama',
            cost: 18,
            currency: 'USD',
            bookingRef: 'SGN-0504',
            status: 'confirmed',
          },
          {
            id: 'k3-2',
            type: 'activity',
            time: '10:30',
            title: 'Arashiyama Bamboo Grove & Tenryu-ji',
            description: 'Walk through the famous towering bamboo forest, then explore Tenryu-ji\'s UNESCO World Heritage Zen garden and its koi-filled pond.',
            location: 'Arashiyama, Kyoto',
            cost: 12,
            currency: 'USD',
            status: 'confirmed',
          },
          {
            id: 'k3-3',
            type: 'activity',
            time: '14:00',
            endTime: '15:30',
            title: 'Private Urasenke Tea Ceremony',
            description: '90-minute intimate tea ceremony in an 18th-century machiya townhouse. Instruction in chakin cloth folding, chasen whisking, and wagashi pairing.',
            location: 'Sagano, Arashiyama',
            cost: 120,
            currency: 'USD',
            bookingRef: 'TC-ARH-0504',
            status: 'confirmed',
          },
          {
            id: 'k3-4',
            type: 'meal',
            time: '18:30',
            title: 'Shoraian: Riverside Tofu Kaiseki',
            description: 'Seasonal tofu cuisine on a wooden deck over the Oi River. Signature yudofu in kombu dashi, cold tofu with yuzu miso, and matcha warabi mochi.',
            location: 'Arashiyama',
            cost: 95,
            currency: 'USD',
            status: 'pending',
          },
        ],
      },
      {
        dayNumber: 4,
        date: 'Monday, May 5',
        dayLabel: 'Philosopher\'s Path & Gion',
        events: [
          {
            id: 'k4-1',
            type: 'activity',
            time: '09:00',
            endTime: '11:30',
            title: 'Philosopher\'s Path Walk',
            description: 'The 2km stone path along a canal lined with cherry trees. Visit Nanzen-ji, Eikan-dō, and Hōnen-in temple along the way.',
            location: 'Higashiyama, Kyoto',
            cost: 0,
            currency: 'USD',
            status: 'confirmed',
          },
          {
            id: 'k4-2',
            type: 'meal',
            time: '12:30',
            title: 'Omen Noodles',
            description: 'Beloved soba noodle restaurant tucked in a traditional Kyoto townhouse. Order the hot udon with seasonal vegetables and sesame dipping sauce.',
            location: 'Okazaki, Kyoto',
            cost: 28,
            currency: 'USD',
            status: 'suggested',
          },
          {
            id: 'k4-3',
            type: 'activity',
            time: '16:00',
            title: 'Gion District & Geiko Spotting',
            description: 'Guided evening walk through Gion\'s preserved Edo-period streets. High chance of seeing geiko and maiko in Hanamikoji Dori at dusk.',
            location: 'Gion, Kyoto',
            cost: 55,
            currency: 'USD',
            bookingRef: 'GWT-KYT-0505',
            status: 'confirmed',
          },
        ],
      },
    ],
  },
  {
    id: '2',
    userId: 'user-1',
    planningProgress: 52,
    slug: 'amalfi-escape',
    title: 'Coastal Serenity in Amalfi',
    destination: 'Positano, Italy',
    country: 'Italy',
    coverImage: 'https://picsum.photos/seed/amalfi-coast/1200/800',
    dates: { start: 'Sep 12, 2026', end: 'Sep 19, 2026' },
    duration: 7,
    status: 'planning',
    budget: { total: 6800, currency: 'USD', breakdown: { lodging: 3200, food: 1600, transport: 800, activities: 1200 } },
    travelers: 2,
    travelType: 'Luxury / Leisure',
    tags: ['Coastal', 'Romance', 'Gastronomy', 'Sailing'],
    aiMatchScore: 94,
    lastEdited: '1 day ago',
    days: [
      {
        dayNumber: 1,
        date: 'Friday, Sep 12',
        dayLabel: 'Arrival on the Amalfi Coast',
        events: [
          {
            id: 'a1-1',
            type: 'flight',
            time: '09:15',
            endTime: '22:40',
            title: 'Flight ATL → NAP via Frankfurt (LH423)',
            description: 'Lufthansa business class. Frankfurt layover ~2h. Total journey ~14h. Lounge access at Hartsfield-Jackson and FRA.',
            location: 'Atlanta → Naples',
            cost: 2200,
            currency: 'USD',
            bookingRef: 'LH-774421',
            status: 'confirmed',
          },
          {
            id: 'a1-2',
            type: 'transport',
            time: '23:30',
            title: 'Private Chauffeur to Positano',
            description: 'Mercedes E-Class with English-speaking driver from Naples Capodichino through the Sorrento peninsula. Complimentary water and prosecco.',
            location: 'Naples Airport → Positano',
            cost: 280,
            currency: 'USD',
            bookingRef: 'TRF-1912',
            status: 'confirmed',
          },
          {
            id: 'a1-3',
            type: 'hotel',
            time: '01:00',
            title: 'Check-in: Le Sirenuse',
            description: 'Legendary 5-star hotel carved into the cliffside. Sea-view suite with private terrace, marble bath, and Bulgari amenities.',
            location: 'Via Cristoforo Colombo, Positano',
            cost: 920,
            currency: 'USD',
            bookingRef: 'SIR-20250912',
            status: 'confirmed',
          },
        ],
      },
      {
        dayNumber: 2,
        date: 'Saturday, Sep 13',
        dayLabel: 'Positano Beach & Sea',
        events: [
          {
            id: 'a2-1',
            type: 'meal',
            time: '08:30',
            title: 'Terrace Breakfast at Le Sirenuse',
            description: 'Morning spread with sfogliatelle, fresh fruit, local cheeses, and Neapolitan espresso while watching fishing boats leave the harbor.',
            location: 'Le Sirenuse Terrace',
            cost: 45,
            currency: 'USD',
            status: 'confirmed',
          },
          {
            id: 'a2-2',
            type: 'activity',
            time: '11:00',
            title: 'Spiaggia Grande Beach',
            description: 'Morning at Positano\'s iconic main beach. Concierge-reserved sun loungers and umbrellas. Snorkel gear provided.',
            location: 'Spiaggia Grande, Positano',
            cost: 60,
            currency: 'USD',
            status: 'confirmed',
          },
          {
            id: 'a2-3',
            type: 'transport',
            time: '13:00',
            title: 'Wooden Boat to Da Adolfo',
            description: 'Iconic red-striped boat transfer to the secluded Laurito Beach — the only way to reach this legendary lunch spot.',
            location: 'Positano Marina → Laurito',
            cost: 10,
            currency: 'USD',
            status: 'confirmed',
          },
          {
            id: 'a2-4',
            type: 'meal',
            time: '13:30',
            title: 'Lunch: Da Adolfo Trattoria',
            description: 'Barefoot beach dining at a Positano institution. Grilled mozzarella with lemon leaves, sea bream, local rosé. No reservations — first come.',
            location: 'Laurito Beach, Positano',
            cost: 120,
            currency: 'USD',
            status: 'suggested',
          },
          {
            id: 'a2-5',
            type: 'meal',
            time: '20:00',
            title: 'Dinner: Ristorante Max (Michelin Bib)',
            description: 'Candlelit terrace at cliff\'s edge. Linguine alle vongole, langoustine with Amalfi lemon, local limoncello to close.',
            location: 'Via dei Mulini, Positano',
            cost: 180,
            currency: 'USD',
            bookingRef: 'MAX-3341',
            status: 'pending',
          },
        ],
      },
      {
        dayNumber: 3,
        date: 'Sunday, Sep 14',
        dayLabel: 'Private Sailing Charter',
        events: [
          {
            id: 'a3-1',
            type: 'activity',
            time: '09:30',
            endTime: '17:00',
            title: 'Full-Day Sailing to Li Galli & Capri',
            description: 'Private 40ft gulet with skipper and deckhand. Anchor at the legendary Li Galli islands (Rudolph Nureyev\'s retreat), snorkel in sea caves, and cruise to Capri for aperitivo.',
            location: 'Positano → Li Galli → Capri',
            cost: 850,
            currency: 'USD',
            bookingRef: 'SAIL-POS-0914',
            status: 'confirmed',
          },
          {
            id: 'a3-2',
            type: 'meal',
            time: '12:00',
            title: 'Onboard Catered Lunch',
            description: 'Fresh antipasti, spaghetti alle cozze, local white wine, fruit, and dolci prepared by the boat\'s private chef.',
            location: 'At anchor, Li Galli',
            cost: 0,
            currency: 'USD',
            status: 'confirmed',
          },
          {
            id: 'a3-3',
            type: 'meal',
            time: '19:30',
            title: 'Sunset Cocktails: La Fontelina, Capri',
            description: 'Aperol spritz on the rocks of the legendary swimming club before returning by water taxi to Positano.',
            location: 'La Fontelina, Capri',
            cost: 75,
            currency: 'USD',
            status: 'suggested',
          },
        ],
      },
    ],
  },
  {
    id: '3',
    userId: 'user-1',
    planningProgress: 100,
    slug: 'bali-retreat',
    title: 'Island Serenity: Bali Wellness',
    destination: 'Ubud, Bali',
    country: 'Indonesia',
    coverImage: 'https://picsum.photos/seed/bali-retreat/1200/800',
    dates: { start: 'Jan 5, 2025', end: 'Jan 15, 2025' },
    duration: 10,
    status: 'completed',
    budget: { total: 3800, currency: 'USD', breakdown: { lodging: 1800, food: 700, transport: 400, activities: 900 } },
    travelers: 1,
    travelType: 'Wellness / Solo',
    tags: ['Wellness', 'Yoga', 'Rice Terraces', 'Temples', 'Spa'],
    aiMatchScore: 91,
    lastEdited: '2 months ago',
    days: [
      {
        dayNumber: 1,
        date: 'Sunday, Jan 5',
        dayLabel: 'Arrival in Bali',
        events: [
          {
            id: 'b1-1',
            type: 'flight',
            time: '23:55',
            endTime: '06:45',
            title: 'Flight JFK → DPS via Singapore (SQ947)',
            description: 'Singapore Airlines Economy Plus with lie-flat seat upgrade. Stopover at Changi T2 — access to free cinema and rooftop pool.',
            location: 'New York JFK → Denpasar',
            cost: 980,
            currency: 'USD',
            bookingRef: 'SQ-241901',
            status: 'confirmed',
          },
          {
            id: 'b1-2',
            type: 'transport',
            time: '08:00',
            title: 'Private Car to Ubud',
            description: 'Air-conditioned car from Ngurah Rai Airport through rice paddy roads to Ubud center. ~1.5 hours.',
            location: 'DPS → Ubud',
            cost: 45,
            currency: 'USD',
            status: 'confirmed',
          },
          {
            id: 'b1-3',
            type: 'hotel',
            time: '10:00',
            title: 'Check-in: Capella Ubud',
            description: 'Luxury tented camp nestled in a jungle gorge. Private tent villa with handcrafted furniture, outdoor bathtub, and direct forest views.',
            location: 'Ubud, Bali',
            cost: 380,
            currency: 'USD',
            bookingRef: 'CAP-20250105',
            status: 'confirmed',
          },
          {
            id: 'b1-4',
            type: 'activity',
            time: '16:00',
            title: 'Balinese Melukat Blessing Ritual',
            description: 'Traditional purification ceremony with resident high priest. Flower offerings, holy water, and incense at the resort\'s private temple.',
            location: 'Capella Ubud Temple',
            cost: 0,
            currency: 'USD',
            status: 'confirmed',
          },
        ],
      },
      {
        dayNumber: 2,
        date: 'Monday, Jan 6',
        dayLabel: 'Sunrise Yoga & Rice Terraces',
        events: [
          {
            id: 'b2-1',
            type: 'activity',
            time: '06:00',
            endTime: '07:30',
            title: 'Sunrise Yoga — Hilltop Platform',
            description: 'Open-air vinyasa session on the treehouse platform overlooking the Ayung River gorge. Led by resident instructor Made Arsa.',
            location: 'Capella Ubud',
            cost: 40,
            currency: 'USD',
            status: 'confirmed',
          },
          {
            id: 'b2-2',
            type: 'meal',
            time: '08:00',
            title: 'Jungle Breakfast',
            description: 'Freshly squeezed jamu, tropical fruit bowls, and Indonesian-style eggs served on your tent\'s private deck.',
            location: 'Capella Ubud',
            cost: 35,
            currency: 'USD',
            status: 'confirmed',
          },
          {
            id: 'b2-3',
            type: 'activity',
            time: '09:30',
            title: 'Tegallalang Rice Terrace Walk',
            description: 'Guided 2-hour walk through UNESCO-listed Tegallalang terraces. Learn the ancient subak irrigation system from a third-generation farmer.',
            location: 'Tegallalang, Ubud',
            cost: 25,
            currency: 'USD',
            status: 'confirmed',
          },
          {
            id: 'b2-4',
            type: 'meal',
            time: '13:00',
            title: 'Sari Organik Farm Lunch',
            description: 'Farm-to-table restaurant in the middle of the rice paddies. Nasi campur with homegrown sambal, tempeh, and fresh coconut water.',
            location: 'Tegallalang',
            cost: 18,
            currency: 'USD',
            status: 'confirmed',
          },
          {
            id: 'b2-5',
            type: 'activity',
            time: '15:30',
            title: 'Traditional Balinese Massage',
            description: '2-hour full-body treatment using ancient Balinese techniques, coconut oil, and frangipani. Followed by herbal steam bath.',
            location: 'Taksu Spa, Ubud',
            cost: 75,
            currency: 'USD',
            bookingRef: 'TSP-0106',
            status: 'confirmed',
          },
        ],
      },
    ],
  },
  {
    id: '4',
    userId: 'user-1',
    planningProgress: 28,
    slug: 'tokyo-weekend',
    title: 'Tokyo Urban Explorer',
    destination: 'Tokyo, Japan',
    country: 'Japan',
    coverImage: 'https://picsum.photos/seed/tokyo-night/1200/800',
    dates: { start: 'Jul 18, 2026', end: 'Jul 21, 2026' },
    duration: 3,
    status: 'draft',
    budget: { total: 2200, currency: 'USD', breakdown: { lodging: 900, food: 600, transport: 400, activities: 300 } },
    travelers: 3,
    travelType: 'Adventure / Group',
    tags: ['Nightlife', 'Street Food', 'Anime', 'Technology', 'Markets'],
    aiMatchScore: 88,
    lastEdited: '5 hours ago',
    days: [
      {
        dayNumber: 1,
        date: 'Friday, Jul 18',
        dayLabel: 'Arrival & Shibuya Night',
        events: [
          {
            id: 't1-1',
            type: 'flight',
            time: '10:00',
            endTime: '14:30',
            title: 'Flight LAX → HND (ANA NH106)',
            description: 'All Nippon Airways nonstop, ~11h. Economy with premium seat selection. Arriving at Haneda Terminal 3.',
            location: 'Los Angeles → Tokyo Haneda',
            cost: 780,
            currency: 'USD',
            bookingRef: 'ANA-559832',
            status: 'pending',
          },
          {
            id: 't1-2',
            type: 'transport',
            time: '15:30',
            title: 'Keikyu Line → Yamanote to Shibuya',
            description: 'Airport Keikyu Line to Shinagawa (35 min), transfer to Yamanote Loop Line to Shibuya (10 min). IC Card recommended.',
            location: 'HND → Shibuya Station',
            cost: 8,
            currency: 'USD',
            status: 'suggested',
          },
          {
            id: 't1-3',
            type: 'hotel',
            time: '16:00',
            title: 'Check-in: Cerulean Tower Tokyu Hotel',
            description: 'Sleek tower hotel in Shibuya. City-view rooms on floors 19–37. Group booking: connecting rooms for party of 3.',
            location: 'Shibuya, Tokyo',
            cost: 750,
            currency: 'USD',
            bookingRef: 'CTT-DRAFT',
            status: 'pending',
          },
          {
            id: 't1-4',
            type: 'activity',
            time: '19:00',
            title: 'Shibuya Crossing at Night',
            description: 'Experience the world\'s busiest intersection under neon and screens. Head up to Shibuya Sky observation deck for the aerial view.',
            location: 'Shibuya Crossing, Tokyo',
            cost: 22,
            currency: 'USD',
            status: 'suggested',
          },
          {
            id: 't1-5',
            type: 'meal',
            time: '21:00',
            title: 'Ramen: Fuunji Tsukemen (Shinjuku)',
            description: 'Legendary thick dipping ramen. Rich pork-chicken blended broth — ranked top 5 in Tokyo. Arrive 15 min early, queue moves fast.',
            location: 'Shinjuku, Tokyo',
            cost: 18,
            currency: 'USD',
            status: 'suggested',
          },
        ],
      },
      {
        dayNumber: 2,
        date: 'Saturday, Jul 19',
        dayLabel: 'Akihabara, Harajuku & Teamlab',
        events: [
          {
            id: 't2-1',
            type: 'activity',
            time: '10:00',
            title: 'Akihabara Electric Town',
            description: 'Multi-floor arcades, retro game shops, anime figure stores, and maid cafes in Tokyo\'s otaku capital. Budget 2–3 hours.',
            location: 'Akihabara, Tokyo',
            cost: 50,
            currency: 'USD',
            status: 'suggested',
          },
          {
            id: 't2-2',
            type: 'meal',
            time: '13:30',
            title: 'Harajuku: Gyoza-ya & Crepes',
            description: 'Late lunch at Harajuku Gyoza Lou (standing bar, boiled gyoza), then Takeshita Street crepes. Group-friendly street eating.',
            location: 'Harajuku, Tokyo',
            cost: 30,
            currency: 'USD',
            status: 'suggested',
          },
          {
            id: 't2-3',
            type: 'activity',
            time: '16:00',
            endTime: '20:00',
            title: 'teamLab Planets (Immersive Art)',
            description: '4 large-scale immersive artworks: wading through water, flower universe room, infinite crystal world. Pre-book tickets online.',
            location: 'Toyosu, Tokyo',
            cost: 32,
            currency: 'USD',
            bookingRef: 'TLP-0719-GROUP',
            status: 'pending',
          },
          {
            id: 't2-4',
            type: 'meal',
            time: '21:00',
            title: 'Izakaya Dinner: Gonpachi (the Kill Bill bar)',
            description: 'Sprawling multi-level izakaya that inspired the anime film. Yakitori, karaage, edamame, and unlimited sake towers.',
            location: 'Nishi-Azabu, Tokyo',
            cost: 55,
            currency: 'USD',
            bookingRef: 'GONP-DRAFT',
            status: 'suggested',
          },
        ],
      },
    ],
  },
]
